version: '3.3'
services:
  postgres:
    image: postgres:14.1
    ports:
      - 5435:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=modsen
  app:
    image: app
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - 8070:8080
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://localhost:5435/modsen
      - DB_USERNAME=root
      - DB_PASSWORD=root